shared:
  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
    - name: merged-stack
      path: "merged-stack"

groups:
- name: ((project))-((env))
  jobs:
  - terraform-plan-ses-((env))
  - terraform-apply-ses-((env))
- name: destroy
  jobs:
  - terraform-destroy

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: terraform-ses-((env))
  type: terraform
  source:
    storage:
      bucket: ((terraform_storage_bucket_name))
      bucket_path: ((terraform_storage_bucket_path))
      region_name: ((aws_default_region))
      access_key_id: ((terraform_storage_access_key))
      secret_access_key: ((terraform_storage_secret_key))
    vars:
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
      env: ((env))
      project: ((project))
      customer: ((customer))
      aws_region: ((aws_default_region))
    env:
      AWS_ACCESS_KEY_ID: ((aws_access_key))
      AWS_DEFAULT_REGION: ((aws_default_region))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

- name: stack-ses-terraform
  type: git
  source:
    uri: https://github.com/cycloid-community-catalog/stack-ses
    branch: ((ses_stack_git_branch))
    check_every: 2m
    paths:
      - /terraform/

- name: catalog-config-terraform
  type: git
  source:
    uri: ((ses_config_git_repository))
    branch: ((ses_config_git_branch))
    check_every: 2m
    private_key: ((ses_config_git_private_key))
    paths:
      - ((ses_config_terraform_path))


jobs:
  - name: terraform-plan-ses-((env))
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:
        - get: stack-ses-terraform
          trigger: true
        - get: catalog-config-terraform
          trigger: true

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: catalog-config-terraform
              path: "config"
            - name: stack-ses-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((ses_config_terraform_path))
            STACK_PATH: terraform

        - put: terraform-ses-((env))
          params:
            env_name: ((project))-((env))
            plan_only: true
            terraform_source: merged-stack/

  - name: terraform-apply-ses-((env))
    build_logs_to_retain: 10
    plan:
      - do:
        # Get the PR on the project #
        - get: stack-ses-terraform
          trigger: false
          passed:
            - terraform-plan-ses-((env))

        - get: catalog-config-terraform
          trigger: false
          passed:
            - terraform-plan-ses-((env))

        - get: terraform-ses-((env))
          trigger: false
          passed:
            - terraform-plan-ses-((env))

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: catalog-config-terraform
              path: "config"
            - name: stack-ses-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((ses_config_terraform_path))
            STACK_PATH: terraform

        - put: terraform-ses-((env))
          params:
            env_name: ((project))-((env))
            run_plan: true
            terraform_source: merged-stack/

  - name: terraform-destroy
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:
          - get: stack-ses-terraform
            trigger: false
          - get: catalog-config-terraform
            trigger: false
          - task: merge-stack-and-config
            config:
              <<: *merge-stack-and-config
              inputs:
              - name: catalog-config-terraform
                path: "config"
              - name: stack-ses-terraform
                path: "stack"
            params:
              CONFIG_PATH: ((ses_config_terraform_path))
              STACK_PATH: terraform

          - put: terraform-ses-((env))
            params:
              action: destroy
              env_name: ((project))-((env))
              terraform_source: merged-stack/
            get_params:
              action: destroy
